### PR TITLE
add script to make module list from run numbers

### PR DESCRIPTION
**Pull request by capalmer85**
@jsalfeld @casarsa @gkrintir I made the module list today.  It is in this directory.  Can one of you please review and merge?

### CODE REVIEW

**Comment by gkrintir** [comment]
Thx Chris! Seems to nicely follow Danek's instructions, in deed.

Maybe we can simply copy paste Danek example in this step-by-step process for future reference ? e.g. 'Look into the file  /pixel/data0/Run_262000/Run_262081/PixelConfigurationKey.txt and note the configuration key number, in this case: 100965' before line 38 in makeVetoList.py etc.

Then simply stylist comment; be good to convert to one name that refers to modules, i.e. either mod\* or module*, whatever you prefer.

Last, what is this 'ROC' string stands for? It is not in the Danek instruction, so we could add an additional comment there, even if dummy string ;D 

PS: Since we have already the list, we could show even tomorrow if this has a significant impact on noCorr x-section. ;D

**Comment by gkrintir** [comment]
Ah, I forgot about the run number list, it contains also runs in addition to FiIll 4634. These fills will be still relevant for the 5 TeV calibration ? Sorry for the naive question

**Comment by capalmer85** [comment]
hi Massimo.  All excellent comments and questions.

I will add the annotations to the code and a README in the new directory
tonight.

ROC = ReadOut Chip
Each module has several ROCs associated to it (I think is it between 4 and
8).  In their detector configuration files they veto particular ROCs.  We
can't bother with the level of granularity.

Addition runs:  you must veto all modules that were there not good for the
whole 5 TeV running period.  Otherwise, you'd view a ROC turning on (off)
as more (less) luminosity.

**Comment by capalmer85** [comment]
@casarsa Instructions have been added.

**Comment by capalmer85** [comment]
@gkrintir Sorry. I don't know why I thought the previous comments were from Massimo. 

As you can see I updated the instructions.  Can you review and merge?

**Comment by gkrintir** [comment]
Nice! Great thanks btw for the script, for sure useful for future and will save much time.

**Pull request merged**
